Fix for Metasploit XML import
This is traceback #2

After making previous change in /models/scheduler.py - to - skaldship.metasploit.pro - this second traceback pops in -

Traceback (most recent call last):
  File "/opt/SPA/web2py/gluon/scheduler.py", line 303, in executor
    result = dumps(_function(*args, **vars))
  File "applications/kvasir/models/scheduler.py", line 238, in scanner_import
    update_hosts=update_hosts,
  File "applications/kvasir/modules/skaldship/metasploit/pro.py", line 207, in process_report_xml
    ip_only = ip_include_list.split('\r\n')
AttributeError: 'list' object has no attribute 'split'

I fixed this by removing the split attribute.
ip_only = ip_include_list

I am not sure if this is the best way but it works fine after this change.